export const QUERY_KEYS = {
  dashboard:         (month: string) => ["dashboard", month],
  dashboardOverview: () => ["dashboard", "overview"],
  transactions:      (filters: object) => ["transactions", filters],
  income:            () => ["income"],
  incomeVariable:    () => ["income", "variable"],
  fixedExpenses:     () => ["expenses", "fixed"],
  variableExpenses:  () => ["expenses", "variable"],
  goals:                   () => ["goals"],
  goal:                    (id: string) => ["goals", id],
  goalContributions:       (id: string) => ["goals", id, "contributions"],
  sinkingFunds:            () => ["sinking-funds"],
  sinkingFund:             (id: string) => ["sinking-funds", id],
  sinkingFundContributions:(id: string) => ["sinking-funds", id, "contributions"],
  budget:            () => ["budget"],
  monthlyReport:     (month: string) => ["reports", "monthly", month],
  ytdReport:         () => ["reports", "ytd"],
  trends:            (months: number) => ["trends", months],
  categories:        () => ["categories"],
  currencies:        () => ["currencies"],
  plan:              (month: string) => ["plan", month],
  projection:        (months: number) => ["projection", months],
} as const

export const ROUTES = {
  login:          "/login",
  register:       "/register",
  forgotPassword: "/forgot-password",
  dashboard:      "/dashboard",
  transactions:   "/transactions",
  budget:         "/budget",
  goals:          "/goals",
  sinkingFunds:   "/sinking-funds",
  reports:        "/reports",
  settings:       "/settings",
} as const
